### ISSUE TITLE
[csolution] question : can we trust the compiler version in cprj ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#220] opened 2022-03-16 16:34 UTC
CPRJ says:
```
  <compilers>
    <compiler name="AC6" version="6.16.0"/>
  </compilers>
```

and indeed in cmsis-toolbox, I have: AC6.6.16.0.cmake
with:
```
set(TOOLCHAIN_ROOT "c:/Keil_v5/ARM/ARMCLANG/bin")
```

But:
```
$ ./armclang.exe --version
Product: MDK Professional 5.36
Component: ARM Compiler 6.16
Tool: armclang [5dfeb700]
```

The version returned by the tool is 6.16, not 6.16.0.

So is the version added in the cprj matching the .cmake file or is it the actual version returned by the tooling ?
I need to capture the real version of the compiler in use, not the cmsis-toolbox settings files.

**Comment by fred-r** [comment] 2022-03-16 17:06
Yes, the exact compiler version is part of the reproducibility.
So we need pack versions (and ideally their path on the disk to be double-sure) and exact compiler versions.

**Comment by VGRSTM** [comment] 2022-03-22 06:35
If I may we have extra issue here according to me see [extra compiler support](https://github.com/Open-CMSIS-Pack/devtools/issues/120#issuecomment-1060396857). I've feeling this one is even more pregnant because escalading up to pdsc ...

**Comment by jkrech** [comment] 2022-03-22 10:17
@VGRSTM and @fred-r can we agree that
a) we are using semantic versioning
b) that we can define mappings from tool versions being provided versus the ones being specified
e.g. Arm Compiler 6 is intentionally skipping the patch version if it does not exist. Therefore AC 6.16 == 6.16.0
c) we currently do not have a scalable tool registry which is responsible for ensuring that an Arm Compiler version 6.16 installation is associated with the meta data being used for selecting this compiler in case of being required by the csolution/cproject.
Please feel free to proposed a specification, develop and contribute such a scalable tools registry.
One existing tool I know of is vcpkg from Microsoft. But also there you are relying on the meta data being correctly mapping between the blob being installed and the version being associated.
Regarding supporting additional Compilers, I don't see where the technical scaling issue is. For me the pre-requisite for adding additional compilers is that we have representatives developing and maintaining the support. We already see that we struggle with the IAR compiler.

**Comment by VGRSTM** [comment] 2022-03-22 12:40
@jkrech 
I agree on semantic versioning of course https://semver.org/

> Regarding supporting additional Compilers, I don't see where the technical scaling issue is

I guess no technical issue. More a pain because adding a compiler is impacting lot of contributions. Not only `devtools` are impacted but CMSIS-Pack side (pdsc, ...) too. 

Right now I'm thinking to LLVM introduction. Of course can be added contributing to current code base but will face issue about existing packs usage at a point thinking condition resolution. Most of GCC compliant components may be LLVM ok too but we may not take benefit of ...

> Please feel free to proposed a specification, develop and contribute such a scalable tools registry

Obviously I agree but still have question myself about: is Open-CMSIS (or at least current under discussion formats like *.yml & .cprj) right place to do such?
I'm fine having *.yml / .cprj dealing with packs, components, devices, ... here we are discussing to extend support to tools. I guess ambition is to ensure build reproducibility and I'm granting such. Locking compiler is one step but not sufficient according to me. If we want so we have to add all third parties build is relying on (cmake & ninja at least).
Could we think having tooling concerns to be managed by Open-CMSIS integrator instead ?  I'm convinced this way Open-CMSIS has to support compiler type but more ? This would helps my components conditions solving problematic too.
If we look at GCC, each vendor may promote its own variant ... no chance / no interest if Open-CMSIS to introduce in a hard coded manner reference to. 
Thinking loud here ... would be happy to get your comment about.

**Comment by fred-r** [comment] 2022-03-22 13:57
I am not sure we need a tool registry to have accurate versions.

When installing cmsis-toolbox, the toolchains are prompted and stored in TOOLCHAIN_ROOT.
Then, I guess it is possible use this variable when creating the CPRJ to check the version ?

**Comment by fred-r** [comment] 2022-03-23 07:57
I think to go forward with this point we need to clarify what we expect:
- from the OpenCMSIS-Pack-spec
- from the vanilla tooling
- the level of freedom given to the tools implementer

As an embedded SW, I need to specify the compiler my code is compatible with (pdsc) and also in a lock file the exact toolchain and settings used for building my project (lock file).

To me, if adding a new compiler requires a change request in the Open-CMSIS-pak-spec, maybe it is acceptable ?
For the versions, I do not know.

We have also to consider the tooling:
- does the vanilla build environment need to support all offered compilers and versions ? Probably not ?
- can we let the tools implementer decide how to manage the toolchains ? Yes, it is probably the best approach ?
- is the current cmsis-toolbox approach fine (user prompted for toolchain paths) ? I guess it is acceptable, now this needs to be used for the lock file to provide accurate information.

To be discussed...

**Comment by ReinhardKeil** [comment] 2022-03-29 13:54
@fred-r to my knowledge all that is needed is a *.cmake file that reflects the compiler / version.
See here: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/toolbox/docs/installation.md#etcsetupcmake
That is what we ship today: https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr/cbuildgen/config

Adding a new compiler version should be pretty simple.

**Comment by ReinhardKeil** [comment] 2023-01-17 15:58
#493 documents how to add a new compiler toolchain. Hence closing this

**Closed by ReinhardKeil** 2023-01-17 15:58 UTC
Labels: discussion done
