### ISSUE TITLE
[projmgr] csolution usage of local_repository.pidx packs for convert, list packs, list components

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#1430] opened 2024-04-05 08:08 UTC
**Describe the bug**
Packs coming from `local_repository.pidx` is inconsistently handled for `convert`, `list packs`, `list components`

**To Reproduce**
toolbox, currently last commit:
```bash
csolution 2.3.0+p1-gd8c10078 (C) 2024 Arm Ltd. and Contributors
```

csolution:
```yml
solution:
    target-types:
        - type: cm33
          device: ARM::ARMCM33
    build-types:
        - type: debug
          compiler: GCC
    projects:
        - project: sw.cproject.yml
    packs:
        - pack: ARM::Cortex_DFP
        - pack: ARM::CMSIS
```

cproject:
```yml
project:
    components:
        - component: ARM::CMSIS:CORE
```

CMSIS_PACK_ROOT:
```
ARM.CMSIS.5.9.0 installed
ARM.Cortex_DFP.1.0.0 installed
ARM.CMSIS.6.0.0 via local_repository.pidx
```

**Expected behavior**

# csolution list packs
This command seems to be slightly odd.
It lists all three packs:
```bash
$ csolution list packs
ARM::CMSIS@6.0.0 (...SOMEWHERE.../armcmsis600/ARM.CMSIS.pdsc)
ARM::CMSIS@5.9.0 (...PACK_ROOT.../ARM/CMSIS/5.9.0/ARM.CMSIS.pdsc)
ARM::Cortex_DFP@1.0.0 (...PACK_ROOT.../ARM/Cortex_DFP/1.0.0/ARM.Cortex_DFP.pdsc)
```
The `ARM.CMSIS.5.9.0` is unexpected here since 6.0.0 is newer

# csolution list components
This command seems to work as expected, it lists components only from `ARM::CMSIS@6.0.0` and `ARM::Cortex_DFP@1.0.0`.
I.e. the "older" `ARM::CMSIS@5.9.0` is not read here since we are not using "--load all"

```bash
$ csolution list components
ARM::CMSIS Driver:CAN:Custom@1.0.0 (ARM::CMSIS@6.0.0)
... snip ...
ARM::Device:IRQ Controller:GIC@1.2.0 (ARM::CMSIS@6.0.0)
ARM::Device:Startup&C Startup@1.2.0 (ARM::Cortex_DFP@1.0.0)
ARM::Device:Startup&C Startup@2.2.0 (ARM::Cortex_DFP@1.0.0)
```

# csolution convert
For the different situations, there are a few different behaviours:

1. `no cbuild-pack.yml` -> `Issue`
	The csolution.yml `pack: ARM::CMSIS` is resolved to `ARM::CMSIS@5.9.0` for components, expected was `ARM::CMSIS@6.0.0`
2. `cbuild-pack.yml locking ARM::CMSIS@6.0.0` -> `OK` 
	The command correctly now resolves csolution.yml `pack: ARM::CMSIS` to `ARM::CMSIS@6.0.0`
3. `no cbuild-pack.yml` and `ARM::CMSIS@6.0.0` explicitly referenced in csolution.yml -> `Small issue`
	The command correctly now resolves csolution.yml `pack: ARM::CMSIS@6.0.0` to `ARM::CMSIS@6.0.0`
	But, the `cbuild-pack.yml` does not contain a `selected-by-pack` for the 6.0.0:
```yml
cbuild-pack:
  resolved-packs:
    - resolved-pack: ARM::CMSIS@6.0.0
    - resolved-pack: ARM::Cortex_DFP@1.0.0
      selected-by-pack:
        - ARM::Cortex_DFP
```
4. `no cbuild-pack.yml` and `no ARM.CMSIS.5.9.0 in CMSIS_PACK_ROOT` -> `Small issue`
	Identical to 3, The command correctly now resolves csolution.yml `pack: ARM::CMSIS@6.0.0` to `ARM::CMSIS@6.0.0`
	But, the `cbuild-pack.yml` does not contain a `selected-by-pack` for the 6.0.0.

**Environment (please complete the following information):**
- Version csolution 2.3.0+p1-gd8c10078
- OS: Linux x86_64

**Comment by jeromecoutant** [comment] 2024-04-05 11:34
Issue has been detected with 2.2.1 version (not a 2.3.0 regression)

**Comment by jkrech** [comment] 2024-04-05 11:44
Are you invoking 
`csolution list packs`
or
`csolution list packs <csolution>.csolution.yml` ?

**Comment by brondani** [comment] 2024-04-05 11:48
I can confirm what is being reported.
Concerning the `list packs` issue it seems the function [`RteKernel::GetInstalledPacks`](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.3.0/libs/rtemodel/src/RteKernel.cpp#L407-L427) correctly find the latest installed packs but the local repository packs are just added to the list without filtering them. @edriouk Is this something would you like to address?

All other issues seem to be related to the cbuild-pack creation mechanism considering only installed packs and not local repository packs when establishing pack requirements:
https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.3.0/tools/projmgr/src/ProjMgrWorker.cpp#L1531-L1548
@Torbjorn-Svensson Would you be willing to address this?

**Comment by slhultgren** [comment] 2024-04-08 09:04
> I can confirm what is being reported. Concerning the `list packs` issue it seems the function [`RteKernel::GetInstalledPacks`](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.3.0/libs/rtemodel/src/RteKernel.cpp#L407-L427) correctly find the latest installed packs but the local repository packs are just added to the list without filtering them. @edriouk Is this something would you like to address?
> 
> All other issues seem to be related to the cbuild-pack creation mechanism considering only installed packs and not local repository packs when establishing pack requirements: https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.3.0/tools/projmgr/src/ProjMgrWorker.cpp#L1531-L1548 @Torbjorn-Svensson Would you be willing to address this?

should the https://github.com/Open-CMSIS-Pack/devtools/blob/f8dacccf5ca7bdcc8ca176bfa6e1e74e9c9a13f1/tools/projmgr/src/ProjMgrWorker.cpp#L1535 be replaced with something from `RteKernel`? possibly a temporary instance of the kernel, since we want to ask "someone", what is the best version to use for a given `VENDOR.NAME[.VERSION]´, and using the `RteFsUtils` is possibly a bit too low-level here?

**Comment by edriouk** [comment] 2024-04-12 14:32
Fixed by introducing `RteKernel::GetEffectivePdscFile()` and `RteKernel::GetEffectivePdscFiles() `methods.
Local pack get visible in all places where  installed packs are required. 
A local pack takes precedence over an installed one if its version is larger or equal than the installed one (withing requested rage).
Corresponding tests has been added.
@slhultgren, could you please validate that the issue is fixed for all aspects

**Closed** 2024-05-27 07:31 UTC
Labels: bug
