### ISSUE TITLE
[csolution] Add flag on `list` commands (e.g. `--json`) to obtain data in a machine readable format

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1159] opened 2023-10-20 12:52 UTC
The output of the listing commands or the commands returning information about the csolution will be used by machine processes to retrieve information about the csolution projects in an abstracted and robust way. Therefore, having the output defined in a machine readable format would greatly improve the robustness of the parsing process.

The format could be `json` and the flag `--json` but could also be any other machine readable format which are considered more suitable.

**Comment by ReinhardKeil** [comment] 2023-10-25 07:03
I think this is a duplicate of #1158 (or is this a clarification of the request)

**Comment by jkrech** [comment] 2023-10-25 07:36
These are two independent change requests:
https://github.com/Open-CMSIS-Pack/devtools/issues/1158 will display devices and boards used by `<solution>.csolution.yml` using the boardID and deviceID notation used by the YAML project format and the origin pack. E.g.:
```
  STMicroelectronics::STM32U5A9VJTxQ (Keil::STM32U5xx_DFP@2.1.0)
  STMicroelectronics::STM32F407IGHx (Keil::STM32F4xx_DFP@2.7.0)
```
This issue requests the output to be e.g. in json format when --json is specified.
```
["STMicroelectronics::STM32U5A9VJTxQ (Keil::STM32U5xx_DFP@2.1.0)", "STMicroelectronics::STM32F407IGHx (Keil::STM32F4xx_DFP@2.7.0)"]
```

**Comment by madchutney** [comment] 2023-10-25 09:02
The JSON would be more machine readable if a key value format was used, e.g. 

```json
[
   {
      "Vendor":"STMicroelectronics",
      "Name":"STM32U5A9VJTxQ",
      "Pack":{
         "Vendor":"Keil",
         "Name":"STM32U5xx_DFP",
         "Version":"2.1.0"
      }
   },
   {
      "Vendor":"STMicroelectronics",
      "Name":"STM32F407IGHx",
      "Pack":{
         "Vendor":"Keil",
         "Name":"STM32F4xx_DFP",
         "Version":"2.7.0"
      }
   }
]
```

**Comment by ReinhardKeil** [comment] 2023-10-25 09:18
I wonder if this approach does not duplicate the content of the [Build Information Files](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md).

Which problem are we trying to address here?

**Comment by madchutney** [comment] 2023-10-25 14:06
There are two problems that we are trying to solve:

1. Interpret a solution / project files to determine the list of devices/boards/toolchains the solution supports.
2. Present that information in a format that be easily read by machine.

**Comment by ReinhardKeil** [comment] 2023-10-27 15:21
We believe the answer is in #1177

**Closed** 2023-11-07 12:45 UTC
Labels: enhancement, discussion, discussion done
