### ISSUE TITLE
[csolution] `compile_commands.json` not referenced in generated `*.cbuild.yml`

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1210] opened 2023-11-15 15:56 UTC
We ran `cbuild` with `-t=database` to generate the compile_commands.json from a csolution project. This file is not referenced in the generated cbuild.yml file as we would expect.
See the files below
[hello.Debug+B-U585I-IOT02A.cbuild.yml.txt](https://github.com/Open-CMSIS-Pack/devtools/files/13366645/hello.Debug%2BB-U585I-IOT02A.cbuild.yml.txt)
[hello.cbuild-idx.yml.txt](https://github.com/Open-CMSIS-Pack/devtools/files/13366646/hello.cbuild-idx.yml.txt)

As can be seen in the file, the output information mentions an hex file and an axf file which actually have not been generated:
```yaml
  output-dirs:
    intdir: tmp/hello/B-U585I-IOT02A/Debug
    outdir: out/hello/B-U585I-IOT02A/Debug
    rtedir: RTE
  output:
    - type: elf
      file: hello.axf
    - type: hex
      file: hello.hex
```

**Comment by jkrech** [comment] 2023-11-21 07:50
Tools reading the cbuild and cbuild-idx files should not make a blind assumption about output files and directories to exist. Just assume a build fails and an axf, lib, bin or hex file is not created. We will not go back and update the cbuild-idx file depending on the success of a build.
Listing the compile_commands.json file as an output file should be feasible. @brondani  what do you think?

**Comment by brondani** [comment] 2023-11-21 10:51
It seems we should clarify and align expectations.

`cbuild-idx.yml` and `cbuild.yml` are the result of the project manager, not the result of the build manager.
They are intended to be the input for the build manager (and in practice they will be the input once cprj will be fully replaced).

`output-dirs` and `output` can be read as the output locations and filenames that will be generated IF you build it.

Calling cbuild with target `database` is clearly not an artifact building task, it generates only the `compile_commands.json`.
It seems this is still an undocumented feature, I guess we should extend the documentation to avoid such misunderstanding.

Generating compile commands is a pure build manager feature, the project manager currently doesn't know about it, so I wouldn't simply add it to project manager results, unless we decide to make the project manager aware of it.

**Comment by jkrech** [comment] 2023-11-21 12:23
Thanks for clarifying.

**Comment by acabarbaye** [comment] 2024-01-09 08:49
@brondani @jkrech Sorry I had completely missed your answers here. From our previous discussions, I understood that to retrieve artefacts produced by a job (whether it is artefacts from builds or for intellisense), I should read the cbuild-idx file to get the cbuild.yml file and from there find out what has been produced. From your answers here, I imagine I had misunderstood the purpose of those two files as they seem to be primarily for internal use of the build process itself and not for describing the result of a job. Is there a way from the output directory to determine what constitutes an output artefact rather than an intermediary build artefact?

**Comment by ReinhardKeil** [comment] 2024-01-09 09:07
@acabarbaye these files are not just for internal use.  They contain details about the build process. IMHO these are the files that the IDE should use to understand the location of build artifacts.

**Comment by acabarbaye** [comment] 2024-01-09 09:32
in that case, should not the `compile_commands.json` files generated for a project be mentioned there as they are the artefacts.

**Comment by ReinhardKeil** [comment] 2024-01-09 09:35
@acabarbaye I agree, we need to make this more useful for IDE usage. Not sure if `compile_commands.json` should be a direct artifact of the CMSIS-Toolbox.

**Comment by acabarbaye** [comment] 2024-01-09 09:45
they are the results of `-t=database` and are produced by CMSIS-Toolbox because they are toolchain specific and require project understanding

**Comment by brondani** [comment] 2024-01-09 14:04
@acabarbaye I believe I understand your point, I would suggest to add it to `cbuild.yml` under the `output` node similarly as the build artifacts:
```
  output:
    - type: database
      file: compile_commands.json
```
But for consistency its presence/absence and the `file` value should be reflected in the CMakeLists.txt generation.
I would suggest to handle this entry in the `cbuild2cmake` but not in the old `cbuildgen` since it would require cprj extensions.

**Comment by ReinhardKeil** [comment] 2024-01-15 12:18
When we add it this way, the `compile_commands.json` file would be created also for stand-alone build systems (i.e. CI, MLOps).

I would recommend to build the IDE specific information as suggested here: https://github.com/Open-CMSIS-Pack/devtools/issues/1265#issuecomment-1887396374 - effectively with a command-line option.

**Comment by jkrech** [comment] 2024-01-16 07:26
@ReinhardKeil - `csolution` is generating the cbuild.yml files. All specified output artifacts will only exist if the corresponding context is `build`. Therefore mentioning a hex or axf file in `cbuild.yml` is no guarantee that this file really exists. I think the same is true for `compile_commands.json` files.

**Comment by ReinhardKeil** [comment] 2024-04-02 13:20
I don't believe this is required.  The files are generated by CMake and therefore it is not that easy to add.
With `cbuild setup` the `compile_commands.json` file is generated in the `out` directory of the related context.

**Comment by ReinhardKeil** [comment] 2024-07-01 06:37
closing this as it appears to be a duplicate of #1426

**Comment by jkrech** [comment] 2024-07-01 07:18
The action remaining from this issue is to add the references to the `compile_commands.json` to the `*.cbuild-idx.yml` file.

**Comment by acabarbaye** [comment] 2024-09-09 10:30
I was trying the `cbuild setup` command with cbuild 2.5 and I cannot see any reference to the location of `compile_commands.json` in `cbuild-idx.yml`
e.g.

```yaml
build-idx:
  generated-by: csolution version 2.5.0
  description: Simple Hello World example for MIMXRT1064-EVK
  csolution: hello.csolution.yml
  tmpdir: tmp
  cprojects:
    - cproject: hello.cproject.yml
  cbuilds:
    - cbuild: hello.Debug+MIMXRT1064-EVK.cbuild.yml
      project: hello
      configuration: .Debug+MIMXRT1064-EVK
```
What the decision on this subject?

**Comment by jkrech** [comment] 2024-09-09 10:51
@acabarbaye this looks like a dangling issue that requires updating:
a) *.cbuild-idx.yml only contains information of the active contexts that have been e.g. called with `cbuild setup -S`
```
  cbuilds:
    - cbuild:
```
b) compile_commands.json is always stored in the output directory. The output directory is specified in the `cbuild.yml` just like for other output artifacts e.g. `<application>.axf` 

```
  outputdirs:
    - outdir:
```

I am not seeing any plans of extending the cbuild-idx.yml file and duplicating the outdir information present in *.cbuild.yml

**Closed by jkrech** 2024-09-09 10:51 UTC
Labels: documentation

**Comment by acabarbaye** [comment] 2024-09-09 11:02
So to clarify @jkrech , there will be no way to list the compile_commands.json other than scanning the filesystem and the only way to associate a compile_commands.json to a context is to look in which directory it is put and check in the cbuild.yml which context that directory refers to?

**Comment by ReinhardKeil** [comment] 2024-09-09 11:31
The file `compile_commands.json` is always in the directory referred by `outputdirs: - outdir:`
