### ISSUE TITLE
How to specify linker binary?

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#357] opened 2022-05-30 14:43 UTC
I have multiple toolchains installed and looks like `cbuild` uses the default `/usr/bin/ld` which does not know the option `--cpu=Cortex-M3` which makes sense, because it's not `armlink`.

How do I set the linker binary path, similarly to AC6 and GCC paths in `./etc/AC6.6.18.0.cmake`? There seems to be no template for the linker.

Thanks!

**Comment by jkrech** [comment] 2022-05-30 16:22
Which build engine are you using? Ninja? Gnu Make?
I do agree that despite the fact that the ./etc/AC6.6.18.0.cmake does not contain any explicit variable setting for the linker binary, still in the rules.ninja on Windows I see the correct path set.

```
in line 16 of the AC6.6.18.0.cmake you could add:
set(LD ${TOOLCHAIN_BIN_DIR}/armlink.${EXT})

and in line 471 you could add:
set(CMAKE_LINKER "${LD}")
```
Does that make any difference?

**Comment by jankap** [comment] 2022-06-07 09:42
Hi, I'm on Ubuntu 22.04 + Cmake v3.22.1 + ninja v1.11.0.

I could fix the wrong default linker by using `set(CMAKE_LINKER "/home/dev/.../armlink")`. This line was added directly on top of `AC6.6.18.0.cmake`.

In you solution, is `$TOOLCHAIN_BIN_DIR` set by cmake automatically? Couldn't find the variable in `AC6.6.18.0.cmake`. I guess it should work, too since my "solution" is simply hard coding which is sufficient for me currently.

How does cmake detect the linker if no `$CMAKE_LINKER` is defined?

**Comment by jkrech** [comment] 2022-06-07 09:57
I am not a CMake expert so cannot tell. @brondani  can you shed some light on $CMAKE_LINKER ?

``
In your solution, is $TOOLCHAIN_BIN_DIR set by cmake automatically? Couldn't find the variable in AC6.6.18.0.cmake. I guess it should work, too since my "solution" is simply hard coding which is sufficient for me currently.
``
Sorry for the confusion, it should read `TOOLCHAIN_ROOT` instead and is defined in line 7.

**Comment by brondani** [comment] 2022-06-07 13:46
In our boiler plate it is CMake itself that finds the suitable linker according to the chosen compiler and language (see https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/CMakeFindBinUtils.cmake).

CMake being able to compile but wrongly trying to use the default linker `/usr/bin/ld` is a symptom of a dirty CMake cache, for example because the toolchain was not correctly configured previously.
@jankap Does cleaning the CMake cache (for example by running `cbuild <project>.cprj --clear` make any difference?
If not, I would appreciate to have more info to reproduce the issue.

A way to help CMake finding the linker is to set the LD variable, for example:
`set(LD ${TOOLCHAIN_ROOT}/armlink${EXT})`

**Comment by jkrech** [comment] 2022-07-04 15:44
@jankap  are you happy to close this issue?

**Comment by jankap** [comment] 2022-07-06 12:20
Can I get this reopened when there's time to reproduce?

Currently, `set(CMAKE_LINKER "/home/dev/.../armlink")` does the trick as a workaround for me.

**Comment by jkrech** [comment] 2022-07-06 12:26
If you need to reopen it you can always create a new one and reference to this issue ID.

**Closed** 2022-07-11 12:18 UTC
Labels: discussion
